# Generated by Django 5.2.10 on 2026-01-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE_PROJECT", "Employee-Project"),
                            ("PROJECT", "Project"),
                            ("EMPLOYEE", "Employee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
    ]
