# Generated by Django 5.2.10 on 2026-01-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=4)),
                ("description", models.TextField(blank=True)),
                (
                    "billing_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshotted rate at entry creation",
                        max_digits=10,
                    ),
                ),
                (
                    "rate_source",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE_PROJECT", "Employee-Project Rate"),
                            ("PROJECT", "Project Rate"),
                            ("EMPLOYEE", "Employee Rate"),
                            ("COMPANY", "Company Default Rate"),
                        ],
                        help_text="Where the billing rate was resolved from",
                        max_length=20,
                    ),
                ),
                ("is_timer_entry", models.BooleanField(default=False)),
                ("timer_started_at", models.DateTimeField(blank=True, null=True)),
                ("timer_stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "time entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
