# Generated by Django 5.2.10 on 2026-01-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("timeentries", "0001_initial"),
        ("timesheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="timesheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="timesheets.timesheet",
            ),
        ),
    ]
