# Generated by Django 5.2.10 on 2026-01-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeentries', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='is_timer_entry',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='timer_started_at',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='timer_stopped_at',
        ),
    ]
